### ISSUE TITLE
[BUG] Another martyria calculation bug

### ISSUE THREAD

**Issue by gugushvili** [danielgarthur/neanes#277]
Unless I did something wrong, in combinations like the one seen here in "toata lumea" the program doesn't seem to realise the diatonic fthora of Pa is on Pa. Probably has something to do with multi-neume combinations.  

https://youtu.be/rzZaJBsD688?si=ospkbVBpmSZz7JNs&t=55

**Comment by gugushvili** [comment]
I now see there have been a bunch of already closed issues related to this behaviour.

**Comment by basil** [comment]
Cannot reproduce on `HEAD` as of commit 117d0f4; this was fixed in the layout service in #252. Playback is another story.

**Comment by gugushvili** [comment]
Correct, I now downloaded the latest release of Neanes and this martyria is fine. Playback is still broken.

I'll close the issue for now.
